### ISSUE TITLE
Question: Do Refresh Tokens Expire? If so, how to handle that?

### ISSUE THREAD

**Issue by Jgordon-pencilwrench** [GabrielDuarteM/semantic-release-chrome#114]
A hopefully simple question about the refresh token. If I understand correctly, a refresh token can expire, but can be used to obtain a new refresh token. I'm concerned that when the refresh token expires, the deploy process will fail in my Github Action because the action isn't able to update the refresh token that I'm storing in my repo's secrets. Is this a valid concern? If yes, how should I handle this?

# Issue

- [x] I have searched the [issues](https://github.com/GabrielDuarteM/semantic-release-chrome/issues) of this repository and believe that this is not a duplicate.

## Your Environment

Github Action

- `semantic-release-chrome` version: 3.2.0
- `node` version: v2.0
- `npm` (or `yarn`) version: 4.1.1

Relevant code or config

```yml
name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout
env:
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - run: yarn build
      - run: yarn test
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: yarn npm audit
      - name: Release
        run: npx semantic-release
```
